name: Update hub
on:
  repository_dispatch:
    types: update
jobs:
  handle-hub-update:
    uses: krishnans2006-classes/actions/.github/workflows/do-hub-update.yml@main
    with:
      sha: ${{ github.event.client_payload.sha }}
      repository: ${{ github.event.client_payload.repository }}
    secrets:
      HUB_UPDATE_PAT: ${{ secrets.HUB_UPDATE_PAT }}
