name: Update submodules
on:
  repository_dispatch:
    types: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.HUB_UPDATE_PAT }}
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --init --recursive --checkout -f --remote -- "${{github.event.client_payload.github.repository}}"
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "deploy: ${{github.event.client_payload.github.repository}} @ ${{github.event.client_payload.github.sha}}"
          git push
