name: Update submodules
on:
  repository_dispatch:
    types: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.HUB_UPDATE_PAT }}
          submodules: recursive
      - name: Determine new submodule SHA
        run: echo "SHORT_SHA=`echo ${{ github.event.client_payload.github.sha }} | cut -c1-7`" >> $GITHUB_ENV
      - name: Determine commit message
        run: echo "COMMIT_MSG=Update ${{ github.event.client_payload.github.repository }} @ ${SHORT_SHA}" >> $GITHUB_ENV
      - name: Update submodules
        run: |
          git submodule update --init --recursive --checkout -f --remote
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "${COMMIT_MSG}"
          git push
